language: cpp
# command to install dependencies
script: ./autogen.sh && ./configure && make test
before_script:
  - ./utils/build_gtest.sh
sudo: false
addons:
  apt:
    packages:
    - build-essential
    - libcurl4-openssl-dev
