language: cpp
# command to install dependencies
script: autoreconf -i && ./configure && make check
before_script:
  - sudo apt-get install libcurl4-openssl-dev build-essential
  - ./utils/build_gtest.sh
